# Generated by Django 3.2 on 2022-11-01 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_animation_contact_pagetext_skils_summary_welcome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skils',
            old_name='icon',
            new_name='icons',
        ),
        migrations.RenameField(
            model_name='skils',
            old_name='name',
            new_name='title',
        ),
    ]
