# Generated by Django 3.2 on 2022-11-01 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20221101_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animation',
            old_name='object',
            new_name='animation',
        ),
    ]
