# Generated by Django 3.2 on 2022-11-01 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_rename_object_animation_animation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skils',
            old_name='icons',
            new_name='image_icon',
        ),
    ]
