# Generated by Django 3.2 on 2022-11-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_skils_url_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='title',
        ),
        migrations.AddField(
            model_name='contact',
            name='number',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='summary_title',
            field=models.TextField(default=True),
        ),
    ]
