# Generated by Django 3.2 on 2022-11-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20221101_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='animation',
            name='url_animation',
            field=models.TextField(default=True),
        ),
    ]
